cloud:
  aws:
    credentials:
      accessKey: ${IAM_ACCESS_KEY}      # AWS IAM AccessKey 적기
      secretKey: ${IAM_SECRET_KEY}  # AWS IAM SecretKey 적기
    s3:
      bucket: seb40-main10-bucket    # ex) marryting-gyunny
      dir:  # ex) /gyunny
    region:
      static: ap-northeast-2
    stack:
      auto: false

feign:
  client:
    config:
      default:
        loggerLevel: FULL

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath*:db/h2/CategoryData.sql
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_ADMIN_EMAIL}
    password: ${MAIL_ADMIN_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


logging:
  level:
    com.project: debug

mail:
  address:
    admin: daeyeo10ganeung1234@gmail.com


jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 1440

redis:
  host: localhost
  port: 6379

#kakao pay
kakao:
  admin:
    key: ${KAKAO_ADMIN_KEY}
  host: https://kapi.kakao.com
  uri:
    pay-process: /api/reserve
  pay:
    ready: /v1/payment/ready
    approve: /v1/payment/approve
    cid: TC0ONETIME
    taxfree: 1000
    cancel: /v1/payment/cancel
    order: /v1/payment/order

default :
  image :
    address : "https://seb40-main10-bucket.s3.ap-northeast-2.amazonaws.com/memberImage/default/TestImage.png"

address:
  local-front: http://localhost:3000
  front-s3: http://daeyeo4u.com
  front-https: https://daeyeo4u.com
  domain: https://backend.daeyeo.shop
  local: http://localhost:8080
