# fe-dev.yml
#
name: Deploy to Production
on:
  push:
    branches:
      - fe-dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install # 나는 npm 사용해서
        working-directory: ./client

      - name: Build
        run: npm run build
        env:
          CI: ''
          REACT_APP_SERVER_BASE_URL: ${{ secrets.REACT_APP_SERVER_BASE_URL }}
          REACT_APP_KAKAO_KEY: ${{ secrets.REACT_APP_KAKAO_KEY }}
        working-directory: ./client

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --region ap-northeast-2 \
            build s3://daeyeo4u.com/ --recursive --acl public-read
        working-directory: ./client
